# Name of your workflow
name: Run Selenium Pytest Suite (Edge on Windows)

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Triggers on push to main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    # Use a Windows virtual machine
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Path points inside the project subfolder
          pip install -r Capstone_Selenium_Pytest/requirements.txt
        # Use PowerShell, the default on Windows runners
        shell: pwsh

      # Step 4: Run Pytest tests using Edge
      - name: Run Pytest with Edge
        run: |
          # Navigate into the project folder first
          cd Capstone_Selenium_Pytest
          # Run pytest specifying edge, Allure, and HTML
          pytest -v --browser edge `
            --alluredir=allure-results `
            --html=reports/github_test_report.html `
            --self-contained-html
        shell: pwsh

      # Step 5: Upload Allure results artifact
      - name: Upload Allure results
        # Run this step even if previous steps fail
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results # Name of the artifact
          # Path relative to repo root, inside the project folder
          path: Capstone_Selenium_Pytest/allure-results
          retention-days: 7 # How long to keep the artifact

      # --- NEW STEP TO UPLOAD HTML REPORT ---
      # Step 6: Upload HTML report
      - name: Upload HTML report
        # Run this step even if previous steps fail
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report # Name of the artifact
          # Path to the generated report
          path: Capstone_Selenium_Pytest/reports/github_test_report.html
          retention-days: 7