# Name of your workflow
name: Run Selenium Pytest Suite

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system dependencies for browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          sudo apt-get install -y google-chrome-stable

      # --- THIS STEP IS MODIFIED ---
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Adjust this path if requirements.txt is in a different folder
          pip install -r Capstone_Selenium_Pytest/requirements.txt

      - name: List files in workspace # Keep for debugging
        run: ls -laR # Use -R to list recursively

      # --- THIS STEP IS MODIFIED (Added cd) ---
      - name: Run Pytest with Chrome (headless)
        run: |
          # Navigate into the project folder first
          cd Capstone_Selenium_Pytest
          pytest -v --browser chrome --alluredir=allure-results

      # --- THIS STEP IS MODIFIED (Adjusted path) ---
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          # Path relative to repo root, inside the project folder
          path: Capstone_Selenium_Pytest/allure-results
          retention-days: 7