# Name of your workflow
name: Run Selenium Pytest Suite

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    # --- CHANGE RUNNER TO WINDOWS ---
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming requirements.txt is at the root of the repo
          # If it's inside Capstone_Selenium_Pytest, use:
          # pip install -r Capstone_Selenium_Pytest/requirements.txt
          pip install -r requirements.txt
        # Use PowerShell default shell on Windows
        shell: pwsh

      # --- REMOVED Linux apt-get step ---

      # --- DEBUGGING STEP (Optional but helpful) ---
      - name: List files in workspace
        run: Get-ChildItem -Recurse
        shell: pwsh # Use PowerShell command

      # Step 4: Run Pytest tests using Edge
      - name: Run Pytest with Edge
        run: |
          # If your tests are inside a subfolder, navigate into it:
          # cd Capstone_Selenium_Pytest
          # Run pytest specifying edge
          pytest -v --browser edge --alluredir=allure-results
        shell: pwsh

      # Step 5: Upload Allure results
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          # Adjust path if allure-results is created inside a subfolder:
          # path: Capstone_Selenium_Pytest/allure-results
          path: allure-results
          retention-days: 7